esphome:
  name: upk2esphome-bk7231n
bk72xx:
  board: generic-bk7231n-qfn32-tuya
logger:
mdns:
api:
  password: ""
ota:
  platform: esphome
  password: ""
wifi:
  ssid: ${{ secrets.wifi_ssid }} 
  password: ${{ secrets.wifi_password }}
  ap:
text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version
output:
  - platform: libretiny_pwm
    id: output_red
    pin: P6
  - platform: libretiny_pwm
    id: output_green
    pin: P7
  - platform: libretiny_pwm
    id: output_blue
    pin: P8
  - platform: libretiny_pwm
    id: output_cold
    pin: P24
  - platform: libretiny_pwm
    id: output_warm
    pin: P26
light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
