esphome:
  name: upk2esphome-bk7231n

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:
web_server:
captive_portal:
mdns:

api:
  password: ""

ota:
  platform: esphome
  password: ""

# NOTE: No Wi‑Fi creds here on purpose (safer public build).
# Device will boot a hotspot (captive portal). You can provision Wi‑Fi later
# from the ESPHome dashboard (“Adopt”) or by joining its AP.
wifi:
  ap:

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P6
  - platform: libretiny_pwm
    id: output_green
    pin: P7
  - platform: libretiny_pwm
    id: output_blue
    pin: P8
  - platform: libretiny_pwm
    id: output_cold
    pin: P24
  - platform: libretiny_pwm
    id: output_warm
    pin: P26

light:
  - platform: rgbww
    id: light_rgbww
    name: Light
    color_interlock: true
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold
    warm_white: output_warm
