name: Build ESPHome firmware (with Wi‑Fi secrets)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ESPHome Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/config \
            ghcr.io/esphome/esphome:latest \
            -s wifi_ssid="${{ secrets.WIFI_SSID }}" \
            -s wifi_password="${{ secrets.WIFI_PASSWORD }}"
            compile upk2esphome-bk7231n.yaml \

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .esphome/build/*/*.bin
            .esphome/build/*/*.uf2
