name: Build ESPHome firmware (fixed Wi‑Fi)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ESPHome Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/config \
            ghcr.io/esphome/esphome:latest \
            compile upk2esphome-bk7231n.yaml
            
- name: List build outputs (debug)
  run: ls -R .esphome/build || true

- name: Upload firmware artifact
  uses: actions/upload-artifact@v4
  with:
    name: firmware
    path: |
      .esphome/build/**/.pioenvs/**/firmware*.bin
      .esphome/build/**/.pioenvs/**/firmware*.uf2

