name: Build ESPHome firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build firmware with ESPHome Docker
        run: >
          docker run --rm
          -v "${{ github.workspace }}":/config
          ghcr.io/esphome/esphome:latest
          compile upk2esphome-bk7231n.yaml

      - name: Collect firmware files
        run: |
          set -euxo pipefail
          mkdir -p dist
          echo "Tree under .esphome:"
          ls -R .esphome || true

          # Find anything that looks like firmware output and copy to dist/
          mapfile -t FILES < <(find .esphome -type f \( -name "firmware*.bin" -o -name "*.bin" -o -name "firmware*.uf2" -o -name "*.uf2" \))
          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "No firmware files found under .esphome. Failing…"
            exit 1
          fi
          for f in "${FILES[@]}"; do
            cp "$f" dist/
          done
          echo "Collected files:"
          ls -l dist

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: dist/*
